### ISSUE TITLE
Question: why MessageChannel?

### ISSUE THREAD

**Issue by linonetwo** [andrewiggins/afterframe#2]
The source is short, but I can't get the point, why delay function call using MessageChannel? 

Why not directly call all the functions inside `requestAnimationFrame`?

**Comment by andrewiggins** [comment]
Hey @linonetwo! Sorry for the delay in response. If you are still curious, check out [this video from Jake on the Chrome team](https://www.youtube.com/watch?v=cCOL7MC4Pl0).

tl;dr: This package is about running code **after** the browser has painted. `requestAnimationFrame` is for running code **before** the browser paints (except in older versions of Edge and IE which Jake calls out above). So this package, combines `rAF` and a `MessageChannel` to run code after the next paint. You could use `rAF` and `setTimeout` to accomplish the same basic idea but I think `MessageChannel` callbacks have a higher priority than `setTimeout` and so `MessageChannel` will more often run right after the paint than `setTimeout`.
